//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDotNet_Task
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_to_Category
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Category Category { get; set; }
    }
}
