//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDotNet_Task
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Blog_to_Category = new HashSet<Blog_to_Category>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Blog_to_Category> Blog_to_Category { get; set; }
    }
}
